import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Artifacts,ArtifactError,type ArtifactView } from '../src/artifacts.ts';
import { ArtifactVersions,ArtifactVersionError,type ArtifactVersionsOptions,type ArtifactVersionReceipt } from '../src/artifact-versions.ts';
import type { IoEvent } from '../src/morphz-adapter.ts';

const binding={ownerId:'owner-fixture',sessionId:'session-fixture',verified:true as const};
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return{promise,resolve};}
function fixture(path=':memory:'){
  const db=new DatabaseSync(path),events:IoEvent[]=[],bytes=new Map<string,Uint8Array>();let authorized=true,reads=0,resolutions=0;
  for(let n=1;n<=4;n++){const data=Buffer.from(`Real fixture content ${n}`),resource=`io-resource:resource_${n}`,eventId=`event-${n}`;bytes.set(resource,data);events.push({io_version:'1',type:n%2?'output.committed':'input.accepted',session_id:binding.sessionId,event_id:eventId,sequence:n,timestamp:`2026-09-30T00:00:0${n}Z`,resources:[{resource_id:resource,source_event_id:eventId,name:`report-${n}.txt`,media_type:'text/plain',size_bytes:data.byteLength,sha256:hash(data)}]});}
  const artifacts=new Artifacts({readResource:async(session,id)=>{assert.equal(session,binding.sessionId);reads++;const data=bytes.get(id);if(!data)throw new ArtifactError(404,'Fixture native bytes missing');return data;}},binding.sessionId,()=>events);
  const hooks:{resolve?:()=>Promise<void>;download?:()=>Promise<void>;override?:()=>Promise<{sessionId:string;artifact:ArtifactView}>}={};
  const options:ArtifactVersionsOptions={db,binding,assertAuthorized:()=>{if(!authorized)throw Error('owner revoked');},resolveArtifact:async id=>{resolutions++;await hooks.resolve?.();if(hooks.override)return hooks.override();const result=await artifacts.download(id);return{sessionId:binding.sessionId,artifact:result.artifact};},downloadArtifact:async id=>{await hooks.download?.();return{sessionId:binding.sessionId,...await artifacts.download(id)};},now:()=>123};
  const store=new ArtifactVersions(options),catalog=artifacts.list();
  return{db,store,options,artifacts,catalog,bytes,events,hooks,reads:()=>reads,resolutions:()=>resolutions,allow:(value:boolean)=>{authorized=value;},close:async()=>{await store.close();db.close();}};
}
const create=(f:ReturnType<typeof fixture>,key='create-document-1',index=0)=>f.store.create({title:'Project notes',artifactId:f.catalog[index]!.id,note:'Initial content',idempotencyKey:key});
const append=(f:ReturnType<typeof fixture>,prior:ArtifactVersionReceipt,key:string,index=1)=>f.store.append(prior.documentAtAdmission.id,{artifactId:f.catalog[index]!.id,note:`Version ${index+1}`,expectedRevision:prior.documentAtAdmission.revision,parentVersionId:prior.version.id,idempotencyKey:key});
const code=(name:string)=>(e:unknown)=>e instanceof ArtifactVersionError&&e.code===name;

test('create stores authoritative document and immutable native provenance without copying bytes',async()=>{const f=fixture();try{const receipt=await create(f);assert.match(receipt.documentAtAdmission.id,/^doc-[a-f0-9-]{36}$/);assert.match(receipt.version.id,/^ver-[a-f0-9-]{36}$/);assert.equal(receipt.version.parentVersionId,null);assert.equal(receipt.documentAtAdmission.revision,1);assert.equal(receipt.version.artifact.sessionId,binding.sessionId);assert.equal(receipt.version.artifact.sourceEventId,'event-1');assert.equal(receipt.version.artifact.sha256,f.catalog[0]!.sha256);assert.equal(receipt.version.artifact.origin,'output');assert.equal(f.reads(),1);assert.equal(f.store.receiptByKey('not-yet-committed'),null);assert.deepEqual(f.store.receiptByKey('create-document-1'),receipt);assert.ok(!JSON.stringify(receipt).includes('Real fixture content'));assert.ok(!JSON.stringify(receipt).includes('io-resource:'));}finally{await f.close();}});
test('append creates an exact ordered immutable parent chain and advances one head',async()=>{const f=fixture();try{const a=await create(f),b=await append(f,a,'append-version-2'),c=await append(f,b,'append-version-3',2),history=f.store.history(a.documentAtAdmission.id);assert.deepEqual(history.versions.map(v=>v.revision),[1,2,3]);assert.deepEqual(history.versions.map(v=>v.parentVersionId),[null,a.version.id,b.version.id]);assert.equal(history.document.currentVersionId,c.version.id);assert.equal(history.document.title,'Project notes');assert.deepEqual(history.versions[0],a.version);assert.equal(b.version.artifact.origin,'input');}finally{await f.close();}});
test('same key returns original receipt after head changes, conflicting payload rejects before native read',async()=>{const f=fixture();try{const a=await create(f),b=await append(f,a,'append-version-2');await append(f,b,'append-version-3',2);const count=f.resolutions();assert.deepEqual(await create(f),a);assert.deepEqual(await append(f,a,'append-version-2'),b);assert.equal(f.resolutions(),count);await assert.rejects(f.store.create({title:'Changed',artifactId:f.catalog[0]!.id,idempotencyKey:'create-document-1'}),code('artifact_version_request_conflict'));await assert.rejects(append(f,a,'append-version-2',3),code('artifact_version_request_conflict'));await assert.rejects(append(f,a,'brand-new-stale-key'),code('artifact_version_head_conflict'));assert.equal(f.resolutions(),count);assert.equal(f.store.get(a.documentAtAdmission.id).revision,3);}finally{await f.close();}});
test('concurrent distinct append keys against one head commit exactly one successor',async()=>{const f=fixture();try{const a=await create(f),began=deferred(),finish=deferred();let arrivals=0;f.hooks.resolve=async()=>{if(++arrivals===2)began.resolve();await finish.promise;};const first=append(f,a,'concurrent-key-1'),second=append(f,a,'concurrent-key-2',2);await began.promise;finish.resolve();const outcomes=await Promise.allSettled([first,second]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);const rejected=outcomes.find(x=>x.status==='rejected')as PromiseRejectedResult;assert.ok(code('artifact_version_head_conflict')(rejected.reason));assert.equal(f.store.history(a.documentAtAdmission.id).versions.length,2);}finally{await f.close();}});
test('concurrent exact keys share one atomic receipt after independent read verification',async()=>{const f=fixture();try{const began=deferred(),finish=deferred();let arrivals=0;f.hooks.resolve=async()=>{if(++arrivals===2)began.resolve();await finish.promise;};const one=create(f),two=create(f);await began.promise;finish.resolve();const[a,b]=await Promise.all([one,two]);assert.deepEqual(a,b);assert.equal(f.store.list().documents.length,1);assert.equal(f.store.history(a.documentAtAdmission.id).versions.length,1);}finally{await f.close();}});
test('unknown/native missing resource or foreign session does not create metadata',async()=>{const f=fixture();try{await assert.rejects(f.store.create({title:'Unknown',artifactId:'0'.repeat(64),idempotencyKey:'unknown-resource'}),ArtifactError);f.hooks.override=async()=>({sessionId:'foreign-session',artifact:f.catalog[0]!});await assert.rejects(create(f),code('artifact_version_resource_scope_denied'));f.hooks.override=async()=>({sessionId:binding.sessionId,artifact:{...f.catalog[0]!,id:f.catalog[1]!.id}});await assert.rejects(create(f),code('artifact_version_resource_invalid'));assert.equal(f.store.list().documents.length,0);assert.equal(f.store.receiptByKey('create-document-1'),null);}finally{await f.close();}});
test('owner revocation after awaited resource verification is checked before transaction writes',async()=>{const f=fixture();try{const began=deferred(),finish=deferred();f.hooks.resolve=async()=>{began.resolve();await finish.promise;};const pending=create(f);await began.promise;f.allow(false);finish.resolve();await assert.rejects(pending,/owner revoked/);assert.equal(f.db.prepare('SELECT count(*) AS n FROM artifact_documents').get()!.n,0);assert.equal(f.db.prepare('SELECT count(*) AS n FROM artifact_version_commands').get()!.n,0);f.allow(true);assert.equal(f.store.receiptByKey('create-document-1'),null);}finally{await f.close();}});
test('failed receipt insertion rolls back document/version/head atomically',async()=>{const f=fixture();try{f.db.exec("CREATE TRIGGER deny_receipt BEFORE INSERT ON artifact_version_commands BEGIN SELECT RAISE(ABORT,'synthetic receipt failure'); END;");await assert.rejects(create(f));assert.equal(f.store.list().documents.length,0);assert.equal(f.db.prepare('SELECT count(*) AS n FROM artifact_document_versions').get()!.n,0);f.db.exec('DROP TRIGGER deny_receipt');const a=await create(f);f.db.exec("CREATE TRIGGER deny_receipt BEFORE INSERT ON artifact_version_commands BEGIN SELECT RAISE(ABORT,'synthetic receipt failure'); END;");await assert.rejects(append(f,a,'failed-append-key'));assert.equal(f.store.get(a.documentAtAdmission.id).revision,1);assert.equal(f.store.history(a.documentAtAdmission.id).versions.length,1);assert.equal(f.store.receiptByKey('failed-append-key'),null);}finally{await f.close();}});
test('restart preserves IDs/ordered history and exact old receipt while Runtime is offline',async()=>{const root=mkdtempSync(join(tmpdir(),'artifact-versions-')),path=join(root,'product.db');const f=fixture(path);const a=await create(f),b=await append(f,a,'append-version-2');await f.close();const restored=fixture(path);try{restored.hooks.resolve=async()=>{throw Error('native offline');};assert.deepEqual(await create(restored),a);assert.deepEqual(await append(restored,a,'append-version-2'),b);assert.deepEqual(restored.store.receiptByKey('create-document-1'),a);assert.equal(restored.store.get(a.documentAtAdmission.id).revision,2);assert.deepEqual(restored.store.history(a.documentAtAdmission.id).versions.map(v=>v.id),[a.version.id,b.version.id]);assert.equal(restored.resolutions(),0);}finally{await restored.close();rmSync(root,{recursive:true,force:true});}});
test('downloads use the saved native reference and missing bytes never become success',async()=>{const f=fixture();try{const a=await create(f),download=await f.store.downloadVersion(a.documentAtAdmission.id,a.version.id);assert.equal(hash(download.bytes),a.version.artifact.sha256);f.bytes.delete('io-resource:resource_1');await assert.rejects(f.store.downloadVersion(a.documentAtAdmission.id,a.version.id),e=>e instanceof ArtifactError&&e.status===404);assert.equal(f.store.get(a.documentAtAdmission.id).revision,1);assert.deepEqual(f.store.receiptByKey('create-document-1'),a);}finally{await f.close();}});
test('changed native provenance and corrupt bytes cannot be delivered as an old version',async()=>{const f=fixture();try{const a=await create(f);f.bytes.set('io-resource:resource_1',Buffer.from('corrupt'));await assert.rejects(f.store.downloadVersion(a.documentAtAdmission.id,a.version.id),ArtifactError);const bytes=Buffer.from('replaced immutable content');f.bytes.set('io-resource:resource_1',bytes);const r=(f.events[0]!.resources as any[])[0];r.sha256=hash(bytes);r.size_bytes=bytes.length;await assert.rejects(f.store.downloadVersion(a.documentAtAdmission.id,a.version.id),code('artifact_version_resource_changed'));}finally{await f.close();}});
test('download checks current owner again after async native byte verification',async()=>{const f=fixture();try{const a=await create(f),began=deferred(),finish=deferred();f.hooks.download=async()=>{began.resolve();await finish.promise;};const download=f.store.downloadVersion(a.documentAtAdmission.id,a.version.id);await began.promise;f.allow(false);finish.resolve();await assert.rejects(download,/owner revoked/);}finally{await f.close();}});
test('bounded pages preserve history order and reject foreign document/version cursors',async()=>{const f=fixture();try{const a=await create(f),b=await append(f,a,'append-version-2'),c=await append(f,b,'append-version-3',2);const first=f.store.history(a.documentAtAdmission.id,{limit:2});assert.equal(first.nextCursor,b.version.id);const last=f.store.history(a.documentAtAdmission.id,{limit:2,after:first.nextCursor!});assert.deepEqual(last.versions.map(v=>v.id),[c.version.id]);assert.equal(last.nextCursor,null);const foreign=await create(f,'second-document-key');assert.throws(()=>f.store.history(a.documentAtAdmission.id,{after:foreign.version.id}),code('artifact_version_not_found'));const page=f.store.list({limit:1});assert.ok(page.nextCursor);assert.equal(f.store.list({limit:1,after:page.nextCursor!}).documents.length,1);assert.throws(()=>f.store.list({limit:51}),code('artifact_version_invalid_request'));const other=new ArtifactVersions({...f.options,binding:{...binding,ownerId:'other-owner'}});assert.equal(other.list().documents.length,0);assert.equal(other.receiptByKey('create-document-1'),null);assert.throws(()=>other.get(a.documentAtAdmission.id),code('artifact_version_not_found'));await other.close();}finally{await f.close();}});
test('unsafe or oversized product text/identity input cannot bypass registered resource selection',async()=>{const f=fixture();try{for(const title of ['', 'a'.repeat(161),'line\nbreak'])await assert.rejects(f.store.create({title,artifactId:f.catalog[0]!.id,idempotencyKey:'invalid-input-key'}),code('artifact_version_invalid_request'));await assert.rejects(f.store.create({title:'Valid',artifactId:f.catalog[0]!.id,note:'x'.repeat(2001),idempotencyKey:'invalid-input-key'}),code('artifact_version_invalid_request'));await assert.rejects(f.store.create({...{title:'Valid',artifactId:f.catalog[0]!.id,idempotencyKey:'invalid-input-key'},sha256:'invented'}as any),code('artifact_version_invalid_request'));assert.equal(f.resolutions(),0);assert.throws(()=>new ArtifactVersions({...f.options,binding:{...binding,verified:false}as any}),code('artifact_version_binding_required'));}finally{await f.close();}});
test('async owner guard rejects before native reads and shutdown waits unresolved verification',async()=>{const f=fixture();try{const unsafe=new ArtifactVersions({...f.options,assertAuthorized:async()=>{throw Error('async denied');}});await assert.rejects(unsafe.create({title:'Test',artifactId:f.catalog[0]!.id,idempotencyKey:'async-guard-key'}),code('artifact_version_guard_must_be_synchronous'));assert.equal(f.resolutions(),0);await unsafe.close();const began=deferred(),finish=deferred();f.hooks.resolve=async()=>{began.resolve();await finish.promise;};const creating=create(f);await began.promise;let closed=false;const closing=f.store.close().then(()=>{closed=true;});await new Promise(r=>setImmediate(r));assert.equal(closed,false);finish.resolve();await assert.rejects(creating,code('artifact_version_closed'));await closing;assert.equal(f.db.prepare('SELECT count(*) AS n FROM artifact_documents').get()!.n,0);}finally{await f.close();}});
test('concurrent same key with different content yields one receipt and a conflict, never two versions',async()=>{const f=fixture();try{const began=deferred(),finish=deferred();let arrivals=0;f.hooks.resolve=async()=>{if(++arrivals===2)began.resolve();await finish.promise;};const one=create(f),two=f.store.create({title:'Different title',artifactId:f.catalog[1]!.id,idempotencyKey:'create-document-1'});await began.promise;finish.resolve();const outcomes=await Promise.allSettled([one,two]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);const error=outcomes.find(x=>x.status==='rejected')as PromiseRejectedResult;assert.ok(code('artifact_version_request_conflict')(error.reason));assert.equal(f.store.list().documents.length,1);}finally{await f.close();}});
test('resolver must return a downloadable bounded catalog resource with the original registered path',async()=>{const f=fixture();try{for(const patch of [{downloadable:false},{sizeBytes:32*1024*1024+1},{downloadPath:'https://foreign.example/file'},{sourceEventId:''}]){f.hooks.override=async()=>({sessionId:binding.sessionId,artifact:{...f.catalog[0]!,...patch}});await assert.rejects(create(f),code('artifact_version_resource_invalid'));}assert.equal(f.store.list().documents.length,0);}finally{await f.close();}});
