import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync}from'node:sqlite';
import {CalendarProposals,CALENDAR_TOOL,CalendarProposalError}from'../src/calendar-proposals.ts';
import {CalendarReminders,previewCalendar,type CalendarRule}from'../src/calendar-reminders.ts';
import type{NativeHostEnvelope}from'../src/native-host-authority.ts';
const rule:CalendarRule={intent:'Daily review',timeZone:'UTC',frequency:'daily',localTime:'09:00',startDate:'2030-01-01',dst:{gap:'skip',overlap:'earlier'},missed:'skip_unsubmitted',resume:'skip_overdue_paused'};
const envelope=(call='call'):NativeHostEnvelope=>({protocol:1,tool:CALENDAR_TOOL,invocation:{job_id:'job',tool_call_id:call,principal_id:'principal',agent_id:'agent',context_id:'context',session_id:'session',thread_id:'thread',target_id:'target-default'},arguments:{action:'propose',rule}});
function fixture(){const db=new DatabaseSync(':memory:'),proposals=new CalendarProposals({db,ownerId:'owner',sessionId:'session',now:()=>1}),native=new Map<string,any>();let creates=0;const calendar=new CalendarReminders({db,binding:{ownerId:'owner',sessionId:'session'},now:()=>Date.parse('2030-01-01T08:00:00Z'),authorize:async()=>{},adapter:{getSchedule:async(_s,id)=>{if(!native.has(id))throw Object.assign(Error(),{status:404});return native.get(id);},createSchedule:async(_s,input)=>{creates++;const r={...input,revision:1,status:'queued' as const,interval_seconds:null,thread_id:`thread-${input.id}`,source_turn_id:`client-schedule-${input.id}`};native.set(input.id,r);return r;},controlSchedule:async()=>{throw Error('not used');}}});return{db,proposals,calendar,creates:()=>creates,close:async()=>{await calendar.close();db.close();}};}
const preview=()=>previewCalendar(rule,Date.parse('2030-01-01T08:00:00Z'),1);
test('native proposal/receipt is deterministic, immutable and never creates a schedule',async()=>{const f=fixture();try{const e=envelope(),a:any=f.proposals.propose(e,rule,preview()),b:any=f.proposals.propose(e,rule,preview());assert.deepEqual(a,b);assert.equal(a.proposal.state,'pending_owner_confirmation');assert.equal(a.scheduling,'not_admitted');assert.equal(f.creates(),0);assert.throws(()=>f.proposals.receipt({...e,arguments:{action:'status',proposalId:a.proposal.proposalId}}),CalendarProposalError);}finally{await f.close();}});
test('owner admission and proposal CAS commit atomically; exact confirmation retry reuses one series',async()=>{const f=fixture();try{const e=envelope(),p:any=(f.proposals.propose(e,rule,preview())as any).proposal,c=f.proposals.confirmation(p.proposalId);const admit=()=>f.proposals.confirmInsideAdmission(p.proposalId,p.revision,p.ruleFingerprint);const series=await f.calendar.create({...rule,idempotencyKey:c.seriesKey},admit);assert.equal(series.id,c.seriesId);assert.equal(f.proposals.read(p.proposalId).state,'admitted');await f.calendar.create({...rule,idempotencyKey:c.seriesKey},admit);assert.equal(f.creates(),1);assert.equal((f.proposals.receipt(e)as any).proposal.state,'pending_owner_confirmation');assert.throws(()=>f.proposals.dismiss(p.proposalId,2,()=>{}),CalendarProposalError);}finally{await f.close();}});
test('failed series insertion rolls back the proposal decision',async()=>{const f=fixture();try{const p:any=(f.proposals.propose(envelope(),rule,preview())as any).proposal,c=f.proposals.confirmation(p.proposalId);f.db.exec("CREATE TRIGGER deny_fixture_series BEFORE INSERT ON calendar_series BEGIN SELECT RAISE(ABORT,'synthetic failure'); END;");await assert.rejects(f.calendar.create({...rule,idempotencyKey:c.seriesKey},()=>f.proposals.confirmInsideAdmission(p.proposalId,p.revision,p.ruleFingerprint)));assert.equal(f.proposals.read(p.proposalId).state,'pending_owner_confirmation');assert.equal(f.proposals.read(p.proposalId).revision,1);assert.equal(f.creates(),0);}finally{await f.close();}});
test('dismissal never revives and owner guard failure changes no state',async()=>{const f=fixture();try{const p:any=(f.proposals.propose(envelope(),rule,preview())as any).proposal;assert.throws(()=>f.proposals.dismiss(p.proposalId,1,()=>{throw Error('revoked');}));assert.equal(f.proposals.read(p.proposalId).state,'pending_owner_confirmation');const d=f.proposals.dismiss(p.proposalId,1,()=>{});assert.equal(d.state,'dismissed');assert.deepEqual(f.proposals.dismiss(p.proposalId,1,()=>{}),d);const c=f.proposals.confirmation(p.proposalId);await assert.rejects(f.calendar.create({...rule,idempotencyKey:c.seriesKey},()=>f.proposals.confirmInsideAdmission(p.proposalId,1,p.ruleFingerprint)),CalendarProposalError);assert.equal(f.creates(),0);}finally{await f.close();}});
test('pending proposals and list outputs are bounded and never cross owner/session',async()=>{const f=fixture();try{for(let n=0;n<20;n++)f.proposals.propose(envelope(`call-${n}`),rule,preview());assert.equal(f.proposals.countPending(),20);assert.throws(()=>f.proposals.propose(envelope('overflow'),rule,preview()),CalendarProposalError);const page=f.proposals.list({limit:5});assert.equal(page.proposals.length,5);assert.ok(page.nextCursor);assert.equal(new CalendarProposals({db:f.db,ownerId:'another',sessionId:'session'}).list().proposals.length,0);}finally{await f.close();}});

test('async dismissal guard fails before state writes and consumes rejected callback',async()=>{const f=fixture();try{const p:any=(f.proposals.propose(envelope(),rule,preview())as any).proposal;assert.throws(()=>f.proposals.dismiss(p.proposalId,1,async()=>{throw Error('fixture rejected async guard');}),e=>e instanceof CalendarProposalError&&e.code==='calendar_proposal_guard_must_be_synchronous');await new Promise(r=>setImmediate(r));assert.equal(f.proposals.read(p.proposalId).state,'pending_owner_confirmation');}finally{await f.close();}});
