import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {CalendarProposals,CALENDAR_TOOL} from '../src/calendar-proposals.ts';
import {CalendarProposalHost} from '../src/calendar-proposal-host.ts';
import {NativeHostAuthority} from '../src/native-host-authority.ts';
const binding={principalId:'principal',agentId:'agent',contextId:'context',sessionId:'session'};const rule={intent:'Review',timeZone:'UTC',frequency:'daily',localTime:'09:00',startDate:'2030-01-01',dst:{gap:'skip',overlap:'earlier'},missed:'skip_unsubmitted',resume:'skip_overdue_paused'};
function fixture(){const db=new DatabaseSync(':memory:'),proposals=new CalendarProposals({db,ownerId:'owner',sessionId:'session'});let reads=0,allowed=true;const seriesLimits:number[]=[];const jobs=new Map<string,any>();const authority=new NativeHostAuthority({baseUrl:'http://127.0.0.1:9999',binding,toolName:CALENDAR_TOOL,fetch:async(url,init)=>{reads++;assert.equal(init?.method,'GET');const p=new URL(String(url)).pathname;if(p.includes('execution-jobs'))return Response.json(jobs.get(decodeURIComponent(p.split('/').at(-1)!)));if(p.includes('/threads/'))return Response.json({snapshot:{thread:{id:'thread',initiating_principal_id:'principal',agent_id:'agent',context_id:'context',session_id:'session',target_id:'target-default',lifecycle:'open',control_state:'active'}}});if(p.endsWith('/principal'))return Response.json({session_id:'session',context_id:'context',principal_id:'principal'});return Response.json({id:'session',context_id:'context',agent_id:'agent'});}});const host=new CalendarProposalHost({authority,proposals,now:()=>Date.parse('2030-01-01T08:00Z'),authorize:async()=>{if(!allowed)throw Error('denied')},listSeries:async input=>{seriesLimits.push(input.limit!);return{series:[]};},seriesForProposal:async()=>null});const envelope=(id:string,args:any)=>{const i={job_id:id,tool_call_id:id+'-call',principal_id:'principal',agent_id:'agent',context_id:'context',session_id:'session',thread_id:'thread',target_id:'target-default'};jobs.set(id,{id,tool_name:CALENDAR_TOOL,tool_call_id:i.tool_call_id,initiating_principal_id:'principal',agent_id:'agent',context_id:'context',session_id:'session',thread_id:'thread',target_id:'target-default',status:'running',cancel_requested_at:null,request:{...args,_morphz_execution_route:{target_id:'target-default',backend_kind:'in_process_local'}}});return{protocol:1,tool:CALENDAR_TOOL,invocation:i,arguments:args}};return{host,db,proposals,jobs,seriesLimits,envelope,reads:()=>reads,revoke:()=>allowed=false,close:async()=>{await host.close();db.close()}};}
test('exact native proof returns pending only; old call replay stays immutable while new status sees dismissal',async()=>{const f=fixture();try{const e=f.envelope('job1',{action:'propose',rule}),first:any=await f.host.handle(e,new AbortController().signal);assert.equal(first.scheduling,'not_admitted');assert.equal(f.db.prepare("SELECT count(*) AS n FROM sqlite_master WHERE name='calendar_series'").get()!.n,0);f.proposals.dismiss(first.proposal.proposalId,1,()=>{});f.jobs.get('job1').status='succeeded';const old=await f.host.handle(e,new AbortController().signal);assert.deepEqual(old,first);const next:any=await f.host.handle(f.envelope('job2',{action:'status',proposalId:first.proposal.proposalId}),new AbortController().signal);assert.equal(next.proposal.state,'dismissed');assert.equal(next.series,null);f.revoke();await assert.rejects(f.host.handle(e,new AbortController().signal));}finally{await f.close()}});
test('forged actions, identity, native tool and native immutable args cannot persist any proposal',async()=>{const f=fixture();try{for(const args of [{action:'confirm',rule},{action:'propose',rule,confirmed:true},{action:'propose',rule,idempotencyKey:'injected'}])await assert.rejects(f.host.handle(f.envelope('bad',args),new AbortController().signal));assert.equal(f.reads(),0);const e=f.envelope('wrong',{action:'propose',rule});await assert.rejects(f.host.handle({...e,invocation:{...e.invocation,principal_id:'other'}},new AbortController().signal));f.jobs.get('wrong').tool_name='host_opendots_connectors';await assert.rejects(f.host.handle(e,new AbortController().signal));f.jobs.get('wrong').tool_name=CALENDAR_TOOL;f.jobs.get('wrong').request.rule={...rule,intent:'Different native request'};await assert.rejects(f.host.handle(e,new AbortController().signal));assert.equal(f.proposals.countPending(),0);}finally{await f.close()}});

test('native series list defaults to its declared 20-row bound',async()=>{const f=fixture();try{await f.host.handle(f.envelope('list-default',{action:'list',kind:'series'}),new AbortController().signal);await f.host.handle(f.envelope('list-smaller',{action:'list',kind:'series',limit:3}),new AbortController().signal);assert.deepEqual(f.seriesLimits,[20,3]);}finally{await f.close();}});
