import test from 'node:test';import assert from 'node:assert/strict';
import {Reminders,ReminderError,type NativeSchedule} from '../src/reminders.ts';
function fixture(){const native=new Map<string,NativeSchedule>();let lost=false;const calls:any[]=[];const adapter={getSchedule:async(s:string,id:string)=>{if(!native.has(id))throw Object.assign(Error(),{status:404});return native.get(id)!;},createSchedule:async(s:string,input:any)=>{calls.push(input);const r={...input,revision:1,status:'queued',interval_seconds:input.interval_seconds??null};native.set(input.id,r);if(lost){lost=false;throw Error('response lost');}return r;},controlSchedule:async(s:string,id:string,input:any)=>{const r=native.get(id)!;if(r.revision!==input.expected_revision)throw Object.assign(Error(),{status:409});const v:NativeSchedule={...r,revision:r.revision+1,status:input.action==='cancel'?'cancelled':input.action==='pause'?'paused':'queued'};native.set(id,v);return v;}};return {service:new Reminders(':memory:',adapter as any,'owned-session'),calls,lose:()=>{lost=true;}};}
const input={intent:'Remind me to review the plan',at:'2030-01-02T09:00:00+08:00',timeZone:'Asia/Shanghai',idempotencyKey:'reminder-key-1'};
test('reminder persists original timezone intent and sends canonical instant to native scheduler',async()=>{const f=fixture();try{const r=await f.service.create(input,0);assert.equal(f.calls[0].not_before,'2030-01-02T01:00:00.000Z');assert.equal(f.service.list()[0].input.timeZone,'Asia/Shanghai');assert.equal(r.status,'queued');}finally{f.service.close();}});
test('lost receipt is reconciled by stable native schedule ID with no second create',async()=>{const f=fixture();try{f.lose();await assert.rejects(f.service.create(input,0),ReminderError);await f.service.create(input,0);assert.equal(f.calls.length,1);assert.equal(f.service.list()[0].state,'confirmed');}finally{f.service.close();}});
test('reminder conflicting keys and naive local dates fail closed',async()=>{const f=fixture();try{await f.service.create(input,0);await assert.rejects(f.service.create({...input,intent:'different'},0),ReminderError);await assert.rejects(f.service.create({...input,at:'2030-01-02T09:00',idempotencyKey:'other-key-1'},0),ReminderError);}finally{f.service.close();}});
test('pause/cancel delegates real revision check and cannot control an unowned schedule',async()=>{const f=fixture();try{const r=await f.service.create(input,0);assert.equal((await f.service.control(r.id,'pause',1)).status,'paused');await assert.rejects(f.service.control(r.id,'cancel',1),ReminderError);await assert.rejects(f.service.control('foreign','cancel',1),ReminderError);}finally{f.service.close();}});
test('impossible calendar dates are rejected instead of normalized',async()=>{const f=fixture();try{await assert.rejects(f.service.create({...input,at:'2030-02-30T09:00:00Z'},0),ReminderError);assert.equal(f.calls.length,0);}finally{f.service.close();}});
test('concurrent retries share one dispatch and never downgrade confirmed receipt',async()=>{const f=fixture();try{const [a,b]=await Promise.all([f.service.create(input,0),f.service.create(input,0)]);assert.equal(a.id,b.id);assert.equal(f.calls.length,1);assert.equal(f.service.list()[0].state,'confirmed');}finally{f.service.close();}});
