import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { VoiceStreamService, VoiceStreamError } from '../src/voice-stream.ts';
import type { SpeechProvider } from '../src/voice-provider.ts';
const signal = () => new AbortController().signal;
const tick = () => new Promise<void>(resolve => setImmediate(resolve));
function deferred<T=void>() { let resolve!:(value:T)=>void; let reject!:(error:unknown)=>void; const promise = new Promise<T>((yes,no)=>{resolve=yes;reject=no;}); return {promise,resolve,reject}; }
function fixture(options: {ready?:Promise<void>;closed?:Promise<void>;context?:()=>Promise<any>;maximumSeconds?:number}={}) {
  let allowed = true, clock = 100000, opens = 0, closes = 0, finishes = 0;
  let result:(text:string,final:boolean)=>void = ()=>{}, error:(text:string)=>void=()=>{};
  const writes:Uint8Array[]=[]; const closed=deferred();
  const provider:SpeechProvider={provider:{id:'doubao',label:'fixture'},configured:()=>true,transcribe:async()=>'',synthesize:async()=>Buffer.alloc(0),openStream(_principal,onResult,onError){opens++;result=onResult;error=onError;return {ready:options.ready??Promise.resolve(),closed:options.closed??closed.promise,write(data){writes.push(data.slice());},finish(){finishes++;},close(){closes++;closed.resolve();}};}};
  const context=options.context??(async()=>({sessionId:'native-session',principalId:'native-principal',events:[]}));
  const service=new VoiceStreamService({enabled:true,provider,context,maximumSeconds:options.maximumSeconds,now:()=>clock});
  const authority={ownerId:'owner',deviceSessionId:'device',assertAuthorized(){if(!allowed)throw new VoiceStreamError('fixture_revoked',401);}};
  const id=randomUUID(); const call=(value:Record<string,unknown>, a=authority,s=signal())=>service.call({id,...value},a,s);
  return {service,provider,authority,id,call,writes,result:(text:string,final=false)=>result(text,final),error:(text:string)=>error(text),revoke(){allowed=false;},setNow(value:number){clock=value;},get opens(){return opens;},get closes(){return closes;},get finishes(){return finishes;}};
}
test('configuration never opens provider; explicit streaming consent and owner device authority are mandatory',async t=>{const f=fixture();t.after(()=>f.service.close());assert.equal(f.service.capabilities().duplex,false);assert.equal(f.service.capabilities().maximumSeconds,60);assert.equal(f.opens,0);await assert.rejects(f.call({action:'open'}),/consent_required/);await assert.rejects(f.call({action:'open',consent:true,principalId:'forged'}),/invalid_request/);await assert.rejects(f.call({action:'open',consent:true},{...f.authority,deviceSessionId:''}),/authority_required/);assert.equal(f.opens,0);const disabled=new VoiceStreamService({enabled:false,provider:f.provider,context:async()=>{throw Error('must not read');}});await assert.rejects(disabled.call({id:f.id,action:'open',consent:true},f.authority,signal()),/unavailable/);await disabled.close();});
test('real service admits ordered PCM and incremental replacement; only exact latest duplicate is acknowledged',async t=>{const f=fixture();t.after(()=>f.service.close());const opened=await f.call({action:'open',consent:true});assert.equal(opened.status,'listening');const read=f.call({action:'read',after:opened.revision});f.result('正在识别');assert.equal((await read).text,'正在识别');const data=[1,0,2,0];await f.call({action:'push',sequence:1,data});await f.call({action:'push',sequence:1,data});assert.equal(f.writes.length,1);assert.deepEqual([...f.writes[0]],[1,0,2,0]);f.result('最终完整替换',true);const done=await f.call({action:'read',after:0});assert.equal(done.status,'complete');assert.equal(done.text,'最终完整替换');assert.equal(done.sentToChat,false);assert.equal(f.closes,1);});
test('changed duplicate and out-of-order PCM fail closed without sending another frame',async t=>{for(const c of [{sequence:1,data:[2,0]},{sequence:3,data:[1,0]}]){const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});await f.call({action:'push',sequence:1,data:[1,0]});await assert.rejects(f.call({action:'push',...c}),/sequence_conflict/);assert.equal(f.writes.length,1);assert.equal(f.closes,1);assert.equal((await f.call({action:'read',after:0})).status,'error');}});
test('frame and request shapes are bounded before provider side effects',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});for(const data of [[],[0],[256,0],[-1,0],Array(6402).fill(0),'raw'])await assert.rejects(f.call({action:'push',sequence:1,data}),/invalid_request/);assert.equal(f.writes.length,0);await assert.rejects(f.call({action:'read',after:-2}),/invalid_request/);});
test('stream IDs are bound to exact owner and browser device, and another device cannot cancel or read',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});for(const a of [{...f.authority,ownerId:'other'},{...f.authority,deviceSessionId:'other'}])for(const action of ['read','cancel'])await assert.rejects(f.call(action==='read'?{action,after:0}:{action},a),/scope_denied/);assert.equal(f.closes,0);await assert.rejects(f.service.call({id:randomUUID(),action:'open',consent:true},f.authority,signal()),/busy/);const other={...f.authority,deviceSessionId:'second'};await assert.rejects(f.service.call({id:randomUUID(),action:'open',consent:true},other,signal()),/busy/);assert.equal(f.opens,1);});
test('cancel before delayed identity resolution prevents provider connection and discards text',async t=>{const gate=deferred<any>();const f=fixture({context:()=>gate.promise});t.after(()=>f.service.close());const opening=f.call({action:'open',consent:true});const rejection=assert.rejects(opening,/cancelled/);await tick();const cancelled=await f.call({action:'cancel'});assert.equal(cancelled.status,'cancelled');gate.resolve({sessionId:'s',principalId:'p',events:[]});await rejection;assert.equal(f.opens,0);});
test('unknown cancellation tombstone prevents a late same-ID open',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'cancel'});assert.equal((await f.call({action:'open',consent:true})).status,'cancelled');assert.equal(f.opens,0);});
test('authorization revoked during async native identity check prevents connection',async t=>{const gate=deferred<any>();const f=fixture({context:()=>gate.promise});t.after(()=>f.service.close());const opening=f.call({action:'open',consent:true});await tick();f.revoke();gate.resolve({sessionId:'s',principalId:'p',events:[]});await assert.rejects(opening);assert.equal(f.opens,0);});
test('revocation at provider result and stale callbacks discard transcript and close stream',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});f.result('private draft');f.revoke();f.result('must not expose');assert.equal(f.closes,1);f.result('late',true);await assert.rejects(f.call({action:'read',after:0}),/revoked/);});
test('aborting a waiting read cancels provider and does not resume after a late result',async t=>{const f=fixture();t.after(()=>f.service.close());const opened=await f.call({action:'open',consent:true});const controller=new AbortController();const read=f.call({action:'read',after:opened.revision},f.authority,controller.signal);controller.abort();await assert.rejects(read);f.result('late',true);const state=await f.call({action:'read',after:0});assert.equal(state.status,'cancelled');assert.equal(state.text,'');assert.equal(f.closes,1);});
test('finish stops admission while final result remains read-only and unsent',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});assert.equal((await f.call({action:'finish'})).status,'finishing');await f.call({action:'finish'});assert.equal(f.finishes,1);await assert.rejects(f.call({action:'push',sequence:1,data:[1,0]}),/not_listening/);f.result('review before sending',true);assert.equal((await f.call({action:'read',after:0})).text,'review before sending');await f.call({action:'cancel'});assert.equal((await f.call({action:'read',after:0})).text,'');});
test('duration and total audio limits prevent unbounded input; hard configuration ceiling is120s',async t=>{assert.throws(()=>fixture({maximumSeconds:121}),/invalid_limit/);const f=fixture({maximumSeconds:1});t.after(()=>f.service.close());await f.call({action:'open',consent:true});for(let sequence=1;sequence<=5;sequence++)await f.call({action:'push',sequence,data:Array(6400).fill(0)});await assert.rejects(f.call({action:'push',sequence:6,data:[0,0]}),/duration_limit/);assert.equal(f.writes.length,5);const g=fixture();t.after(()=>g.service.close());await g.call({action:'open',consent:true});g.setNow(160000);await assert.rejects(g.call({action:'push',sequence:1,data:[0,0]}),/duration_limit/);assert.equal(g.writes.length,0);});
test('finish, idle and automatic capture deadline are bounded even if fixture provider stays silent',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});f.setNow(160000);await new Promise(r=>setTimeout(r,270));assert.equal(f.finishes,1);f.setNow(172000);await new Promise(r=>setTimeout(r,270));assert.equal((await f.call({action:'read',after:0})).errorCode,'voice_stream_finish_timeout');const g=fixture();t.after(()=>g.service.close());await g.call({action:'open',consent:true});g.setNow(115001);await new Promise(r=>setTimeout(r,270));assert.equal((await g.call({action:'read',after:0})).errorCode,'voice_stream_idle_timeout');});
test('provider error text is redacted and no stream is retried automatically',async t=>{const f=fixture();t.after(()=>f.service.close());await f.call({action:'open',consent:true});f.error('SECRET_PROVIDER_ECHO');const state=await f.call({action:'read',after:0});assert.equal(state.errorCode,'voice_stream_provider_failed');assert.ok(!JSON.stringify(state).includes('SECRET'));await f.call({action:'open',consent:true});assert.equal(f.opens,1);});
test('close aborts pending identity checks and awaits admitted provider closure',async()=>{const never=new Promise<any>(()=>{});const f=fixture({context:()=>never});const opening=f.call({action:'open',consent:true});await tick();const rejection=assert.rejects(opening);await f.service.close();await rejection;assert.equal(f.opens,0);const gate=deferred();const g=fixture({closed:gate.promise});await g.call({action:'open',consent:true});let done=false;const closing=g.service.close().then(()=>{done=true;});await tick();assert.equal(done,false);gate.resolve();await closing;assert.equal(g.closes,1);await assert.rejects(g.call({action:'open',consent:true}),/closed/);});
test('unconfirmed socket closure is surfaced honestly and asynchronous authorization hooks reject',async t=>{const gate=deferred();const f=fixture({closed:gate.promise});t.after(()=>f.service.close());await f.call({action:'open',consent:true});const cancel=f.call({action:'cancel'});gate.reject(Error('sensitive socket detail'));const state=await cancel;assert.equal(state.status,'error');assert.equal(state.errorCode,'voice_stream_close_unconfirmed');assert.equal(state.text,'');const g=fixture();t.after(()=>g.service.close());await assert.rejects(g.call({action:'open',consent:true},{...g.authority,assertAuthorized:async()=>{throw Error('private');}}),/synchronous/);assert.equal(g.opens,0);});

test('device revocation immediately closes only the exact stream and rejects a pending open',async()=>{const gate=deferred<any>();const f=fixture({context:()=>gate.promise});const opening=f.call({action:'open',consent:true});const rejected=assert.rejects(opening,/cancelled/);await tick();await f.service.revokeSessions('unrelated');assert.equal(f.opens,0);await f.service.revokeSessions('device');await rejected;gate.resolve({sessionId:'s',principalId:'p',events:[]});await tick();assert.equal(f.opens,0);await f.service.close();const g=fixture();await g.call({action:'open',consent:true});await g.service.revokeSessions('other');assert.equal(g.closes,0);await g.service.revokeSessions();assert.equal(g.closes,1);await g.service.close();});

test('revoking an opening provider fences a nonsettling readiness promise and drains its closure',async()=>{const f=fixture({ready:new Promise<void>(()=>{})});const opening=f.call({action:'open',consent:true});const rejected=assert.rejects(opening,/cancelled/);await tick();assert.equal(f.opens,1);await f.service.revokeSessions('device');await rejected;assert.equal(f.closes,1);await f.service.close();});

test('a provider closure rejected without an Error still remains unconfirmed',async()=>{const gate=deferred();const f=fixture({closed:gate.promise});await f.call({action:'open',consent:true});const cancelled=f.call({action:'cancel'});gate.reject(undefined);assert.equal((await cancelled).errorCode,'voice_stream_close_unconfirmed');await f.service.close();});
