import test from 'node:test';
import assert from 'node:assert/strict';
import { encodeMonoWav, resampleMono, createVoiceCapture } from '../public/voice-capture.js';

test('PCM converts to bounded signed mono WAV with clipping',()=>{const wav=encodeMonoWav(new Float32Array([-2,0,2,NaN]),16000);const v=new DataView(wav);assert.equal(v.getUint32(24,true),16000);assert.equal(v.getUint16(22,true),1);assert.equal(v.getInt16(44,true),-32768);assert.equal(v.getInt16(48,true),32767);assert.equal(v.getInt16(50,true),0);assert.equal(wav.byteLength,52);});
test('48k mono resamples to exact 16k sample count',()=>{const output=resampleMono(new Float32Array(48000).fill(0.5),48000);assert.equal(output.length,16000);assert.equal(output[100],0.5);});
test('import/factory never requests mic; late permission after cancel stops all tracks',async()=>{let calls=0,stopped=0,grant:any;const pending=new Promise(r=>grant=r);const capture=createVoiceCapture({mediaDevices:{getUserMedia:()=>{calls++;return pending}},AudioContext:class {},AudioWorkletNode:class {}});assert.equal(calls,0);const start=capture.start();await new Promise(r=>setImmediate(r));assert.equal(calls,1);await capture.cancel();grant({getTracks:()=>[{stop(){stopped++}},{stop(){stopped++}}]});await assert.rejects(start,/cancelled/);assert.equal(stopped,2);assert.equal(capture.active,false);});
test('recording stop releases tracks/context and returns 16k WAV only',async()=>{let stopped=0,closed=0,node:any;class Context{sampleRate=48000;state='running';destination={};audioWorklet={addModule:async()=>{}};createMediaStreamSource(){return {connect(){},disconnect(){}}}createGain(){return {gain:{value:1},connect(){},disconnect(){}}}async resume(){}async close(){closed++;this.state='closed'}}class Worklet{port:any={onmessage:null,close(){}};constructor(){node=this}connect(){}disconnect(){}}const capture=createVoiceCapture({mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped++}}]})},AudioContext:Context,AudioWorkletNode:Worklet});await capture.start();node.port.onmessage({data:new Float32Array(4800).fill(.1)});const audio=await capture.stop();assert.equal(stopped,1);assert.equal(closed,1);assert.equal(capture.active,false);assert.equal(audio.size,3244);assert.equal(new DataView(await audio.arrayBuffer()).getUint32(24,true),16000);await capture.cancel();assert.equal(stopped,1);});
test('worklet setup failure cleans acquired microphone tracks',async()=>{let stopped=0;class Context{state='running';audioWorklet={addModule:async()=>{throw new Error('worklet blocked')}};async close(){this.state='closed'}}const capture=createVoiceCapture({mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped++}}]})},AudioContext:Context,AudioWorkletNode:class {}});await assert.rejects(capture.start(),/worklet blocked/);assert.equal(stopped,1);});
test('sample limit stops microphone even without UI limit callback',async()=>{let stopped=0,node:any;class Context{sampleRate=16000;state='running';destination={};audioWorklet={addModule:async()=>{}};createMediaStreamSource(){return {connect(){},disconnect(){}}}createGain(){return {gain:{value:0},connect(){},disconnect(){}}}async resume(){}async close(){this.state='closed'}}class Worklet{port:any={onmessage:null,close(){}};constructor(){node=this}connect(){}disconnect(){}}const capture=createVoiceCapture({maxSeconds:1,mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped++}}]})},AudioContext:Context,AudioWorkletNode:Worklet});await capture.start();node.port.onmessage({data:new Float32Array(20000)});assert.equal(stopped,1);assert.equal(capture.active,false);const blob=await capture.stop();assert.equal(blob.size,32044);});
