import { createHash } from 'node:crypto';
import type { SpeechDuplex, SpeechProvider } from '../vendor/app-speech/speech.ts';
import type { VoiceContext } from './voice-service.ts';

/** Product lifecycle adapted from Morphz application SpeechStreams at
 * 7e8f7d81f8b00fd45544d94d5b9a321214633df1. Provider protocol remains upstream.
 * Copyright 2026 Newvar and the Morphz contributors. Apache-2.0.
 */
export class VoiceStreamError extends Error { readonly status: number; readonly code: string; constructor(code: string, status = 400) { super(code); this.code = code; this.status = status; } }
export const voiceStreamLimits = { frameBytes: 6400, frameMilliseconds: 200, maximumPendingBytes: 32000, defaultSeconds: 60, hardMaximumSeconds: 120, maximumText: 30000, idleMilliseconds: 15000, readMilliseconds: 5000, terminalMilliseconds: 30000, entries: 128 } as const;
export type VoiceStreamCommand = { id: string; action: 'open'; consent: true } | { id: string; action: 'push'; sequence: number; data: number[] | Uint8Array } | { id: string; action: 'read'; after: number } | { id: string; action: 'finish' | 'cancel' };
export interface VoiceStreamAuthority { ownerId: string; deviceSessionId: string; assertAuthorized: () => void }
export interface VoiceStreamState { id: string; revision: number; status: 'opening' | 'listening' | 'finishing' | 'complete' | 'cancelled' | 'error'; text: string; receivedSequence: number; expiresAt: number; maximumSeconds: number; reviewRequired: true; sentToChat: false; duplex: false; errorCode?: string }
export interface VoiceStreamOptions { enabled: boolean; provider?: SpeechProvider; context: () => Promise<VoiceContext>; maximumSeconds?: number; now?: () => number }
type Entry = { abort: AbortController; authority: VoiceStreamAuthority; state: VoiceStreamState; principalId?: string; sessionId?: string; duplex?: SpeechDuplex; ready?: Promise<void>; closure?: Promise<void>; digest?: string; lastAudio: number; audioBytes: number; finishingAt?: number; wake?: () => void; timer?: ReturnType<typeof setInterval>; expiry?: ReturnType<typeof setTimeout> };
const terminal = (entry: Entry) => ['complete', 'cancelled', 'error'].includes(entry.state.status);
function ensure(condition: unknown, code = 'voice_stream_invalid_request', status = 400): asserts condition { if (!condition) throw new VoiceStreamError(code, status); }
function checkAuthority(authority: VoiceStreamAuthority) { ensure(authority && typeof authority.ownerId === 'string' && !!authority.ownerId && typeof authority.deviceSessionId === 'string' && !!authority.deviceSessionId && typeof authority.assertAuthorized === 'function', 'voice_stream_authority_required', 403); const result = authority.assertAuthorized() as unknown; if (result !== undefined) { if (result && typeof (result as {then?: unknown}).then === 'function') void Promise.resolve(result).catch(() => {}); throw new VoiceStreamError('voice_stream_guard_must_be_synchronous', 500); } }
function parse(raw: unknown): VoiceStreamCommand { ensure(raw && typeof raw === 'object' && !Array.isArray(raw)); const c = raw as Record<string, unknown>; ensure(typeof c.id === 'string' && /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(c.id)); const fields = c.action === 'open' ? ['id','action','consent'] : c.action === 'push' ? ['id','action','sequence','data'] : c.action === 'read' ? ['id','action','after'] : ['id','action']; ensure(['open','push','read','finish','cancel'].includes(String(c.action)) && Object.keys(c).every(key => fields.includes(key))); if(c.action === 'open') ensure(c.consent === true,'voice_stream_consent_required'); if(c.action === 'read') ensure(Number.isSafeInteger(c.after) && Number(c.after) >= -1); if(c.action === 'push') { ensure(Number.isSafeInteger(c.sequence) && Number(c.sequence) > 0); ensure(c.data instanceof Uint8Array || (Array.isArray(c.data) && c.data.every(v => Number.isInteger(v) && v >= 0 && v <= 255))); const data = c.data as number[] | Uint8Array; ensure(data.length > 0 && data.length <= voiceStreamLimits.frameBytes && data.length % 2 === 0); } return c as unknown as VoiceStreamCommand; }

function bounded<T>(work: Promise<T>, signal: AbortSignal | undefined, milliseconds: number, code: string): Promise<T> { return new Promise((resolve,reject)=>{ let settled=false; const done=(success:boolean,value:unknown)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);success?resolve(value as T):reject(value);};const abort=()=>done(false,new VoiceStreamError('voice_stream_cancelled',499));const timer=setTimeout(()=>done(false,new VoiceStreamError(code,502)),milliseconds);signal?.addEventListener('abort',abort,{once:true});work.then(value=>done(true,value),error=>done(false,error));if(signal?.aborted)abort(); }); }

/** Ephemeral dictation only. Never stores audio/text in SQLite or dispatches chat. */
export class VoiceStreamService {
  private options: VoiceStreamOptions; private entries = new Map<string, Entry>(); private pending = new Set<Promise<unknown>>(); private stopped = false; private lifecycle = new AbortController(); private closePromise?: Promise<void>; private maximumSeconds: number; private now: () => number;
  constructor(options: VoiceStreamOptions) { this.options = options; this.maximumSeconds = options.maximumSeconds ?? 60; ensure(Number.isInteger(this.maximumSeconds) && this.maximumSeconds >= 1 && this.maximumSeconds <= 120, 'voice_stream_invalid_limit'); this.now = options.now ?? Date.now; }
  capabilities() { const available = this.options.enabled && this.options.provider?.configured() === true && typeof this.options.provider.openStream === 'function'; return { enabled: this.options.enabled, configured: this.options.provider?.configured() === true, available, streamingDictation: available, duplex: false as const, maximumSeconds: this.maximumSeconds, hardMaximumSeconds: 120, sampleRate: 16000, channels: 1, bitsPerSample: 16, maximumFrameBytes: 6400, frameMilliseconds: 200, maximumPendingBytes: 32000, reviewRequired: true, automaticSend: false, automaticReconnect: false, audioStored: false, transcriptStored: false, verification: 'configuration_only' as const }; }
  private check(entry: Entry, authority: VoiceStreamAuthority) { ensure(entry.authority.ownerId === authority.ownerId && entry.authority.deviceSessionId === authority.deviceSessionId, 'voice_stream_scope_denied', 403); try { checkAuthority(entry.authority); checkAuthority(authority); } catch (error) { this.end(entry, 'cancelled'); throw error; } }
  private update(entry: Entry, change: Partial<VoiceStreamState>) { entry.state = { ...entry.state, ...change, revision: entry.state.revision + 1 }; entry.wake?.(); }
  private end(entry: Entry, status: 'complete' | 'cancelled' | 'error', errorCode?: string) { if(status !== 'complete') entry.abort.abort(); if (!terminal(entry) || status === 'cancelled') this.update(entry, { status, ...(status === 'cancelled' ? { text: '' } : {}), ...(errorCode ? { errorCode } : {}) }); entry.digest = undefined; clearInterval(entry.timer); entry.timer = undefined; if (entry.duplex && !entry.closure) { const duplex = entry.duplex; try { duplex.close(); } catch { this.update(entry, {status:'error',text:'',errorCode:'voice_stream_close_unconfirmed'}); } entry.closure = bounded(duplex.closed,undefined,2500,'voice_stream_close_unconfirmed').catch(() => { this.update(entry, {status:'error',text:'',errorCode:'voice_stream_close_unconfirmed'}); }); } if (!entry.expiry) { entry.expiry = setTimeout(() => { this.entries.delete(entry.state.id); entry.state.text = ''; }, voiceStreamLimits.terminalMilliseconds); entry.expiry.unref(); } }
  private create(id: string, authority: VoiceStreamAuthority): Entry { ensure(this.entries.size < 128, 'voice_stream_busy', 429); const now = this.now(); const entry: Entry = { abort: new AbortController(), authority, state: { id, revision: 0, status: 'opening', text: '', receivedSequence: 0, expiresAt: now + this.maximumSeconds * 1000, maximumSeconds: this.maximumSeconds, reviewRequired: true, sentToChat: false, duplex: false }, lastAudio: now, audioBytes: 0 }; this.entries.set(id, entry); return entry; }
  private async open(entry: Entry, signal: AbortSignal) { signal = AbortSignal.any([signal,entry.abort.signal]); try { const context = await this.awaitContext(signal); signal.throwIfAborted(); checkAuthority(entry.authority); if (terminal(entry) || this.stopped) return; ensure(context && typeof context.principalId === 'string' && !!context.principalId && typeof context.sessionId === 'string' && !!context.sessionId, 'voice_stream_identity_unavailable', 503); ensure(![...this.entries.values()].some(other => other !== entry && other.principalId === context.principalId && !terminal(other)), 'voice_stream_busy', 409); entry.principalId = context.principalId; entry.sessionId = context.sessionId; const provider = this.options.provider!; entry.duplex = provider.openStream!(context.principalId, (text, final) => { if (terminal(entry) || this.stopped) return; try { checkAuthority(entry.authority); ensure(typeof text === 'string' && text.length <= 30000, 'voice_stream_provider_invalid', 502); if (text !== entry.state.text) this.update(entry, {text}); if (final) this.end(entry,'complete'); } catch { this.end(entry,'cancelled'); } }, () => this.end(entry,'error','voice_stream_provider_failed'));
      if (terminal(entry) || this.stopped) { this.end(entry,this.stopped ? 'cancelled' : entry.state.status as 'complete'|'cancelled'|'error'); return; }
      entry.timer = setInterval(() => { if (terminal(entry)) return; try { checkAuthority(entry.authority); } catch { this.end(entry,'cancelled'); return; } if(entry.state.status === 'finishing' && this.now() - (entry.finishingAt ?? this.now()) >= 12000) { this.end(entry,'error','voice_stream_finish_timeout'); } else if(this.now() >= entry.state.expiresAt) { if(entry.state.status === 'listening') { entry.finishingAt = this.now(); this.update(entry,{status:'finishing'}); try { entry.duplex!.finish(); } catch { this.end(entry,'error','voice_stream_provider_failed'); } } else if(entry.state.status === 'opening') this.end(entry,'error','voice_stream_open_timeout'); } else if(this.now() - entry.lastAudio > 15000) this.end(entry,'error','voice_stream_idle_timeout'); }, 250); entry.timer.unref();
      await bounded(entry.duplex.ready,signal,12000,'voice_stream_open_timeout'); signal.throwIfAborted(); checkAuthority(entry.authority); if(!terminal(entry) && entry.state.status === 'opening') this.update(entry,{status:'listening'});
    } catch(error) { if(!terminal(entry)) this.end(entry, signal.aborted || this.stopped ? 'cancelled' : 'error', signal.aborted || this.stopped ? undefined : 'voice_stream_open_failed'); if(error instanceof VoiceStreamError) throw error; throw new VoiceStreamError(signal.aborted || this.stopped ? 'voice_stream_cancelled' : 'voice_stream_open_failed', signal.aborted || this.stopped ? 499 : 502); } }
  private async awaitContext(signal: AbortSignal): Promise<VoiceContext> { signal.throwIfAborted(); return bounded(Promise.resolve().then(()=>{signal.throwIfAborted();return this.options.context();}),signal,10000,'voice_stream_identity_unavailable'); }
  call(raw: unknown, authority: VoiceStreamAuthority, signal: AbortSignal): Promise<VoiceStreamState> { const operation = this.perform(raw,authority,AbortSignal.any([signal,this.lifecycle.signal])); this.pending.add(operation); void operation.finally(() => this.pending.delete(operation)).catch(() => {}); return operation; }
  private async perform(raw: unknown, authority: VoiceStreamAuthority, signal: AbortSignal): Promise<VoiceStreamState> { ensure(!this.stopped,'voice_stream_closed',503); checkAuthority(authority); signal.throwIfAborted(); const command = parse(raw); let entry = this.entries.get(command.id); if(entry) this.check(entry,authority); else { if(command.action === 'cancel') { entry = this.create(command.id,authority); this.end(entry,'cancelled'); return {...entry.state}; } ensure(command.action === 'open','voice_stream_not_found',404); ensure(this.capabilities().available,'voice_stream_unavailable',503); ensure(![...this.entries.values()].some(other => other.authority.ownerId === authority.ownerId && other.authority.deviceSessionId === authority.deviceSessionId && !terminal(other)),'voice_stream_busy',409); entry = this.create(command.id,authority); }
    const current = entry; const abort = () => this.end(current,'cancelled'); signal.addEventListener('abort',abort,{once:true});
    try { if(command.action === 'open') { if(!current.ready && !terminal(current)) current.ready = this.open(current,signal); await current.ready; }
      else if(command.action === 'cancel') this.end(current,'cancelled');
      else if(command.action === 'push') { ensure(current.state.status === 'listening','voice_stream_not_listening',409); const data = Uint8Array.from(command.data); const digest = createHash('sha256').update(data).digest('hex'); if(command.sequence === current.state.receivedSequence && digest === current.digest) { data.fill(0); return {...current.state}; } if(command.sequence !== current.state.receivedSequence + 1) { this.end(current,'error','voice_stream_sequence_conflict'); throw new VoiceStreamError('voice_stream_sequence_conflict',409); } if(this.now() >= current.state.expiresAt || current.audioBytes + data.length > this.maximumSeconds * 32000) { data.fill(0); this.end(current,'error','voice_stream_duration_limit'); throw new VoiceStreamError('voice_stream_duration_limit',409); } this.check(current,authority); try { current.duplex!.write(data); } catch { this.end(current,'error','voice_stream_provider_failed'); throw new VoiceStreamError('voice_stream_provider_failed',502); } finally { data.fill(0); } current.digest = digest; current.audioBytes += command.data.length; current.lastAudio = this.now(); this.update(current,{receivedSequence:command.sequence}); }
      else if(command.action === 'finish' && current.state.status === 'listening') { current.finishingAt = this.now(); this.update(current,{status:'finishing'}); current.lastAudio = this.now(); try { current.duplex!.finish(); } catch { this.end(current,'error','voice_stream_provider_failed'); throw new VoiceStreamError('voice_stream_provider_failed',502); } }
      else if(command.action === 'read' && !terminal(current) && command.after >= current.state.revision) { ensure(!current.wake,'voice_stream_read_busy',409); await new Promise<void>(resolve => { const done = () => { clearTimeout(timer); if(current.wake === done) current.wake = undefined; resolve(); }; const timer = setTimeout(done,5000); current.wake = done; }); }
      signal.throwIfAborted(); this.check(current,authority); if(terminal(current)) await current.closure; signal.throwIfAborted(); this.check(current,authority); return {...current.state};
    } finally { signal.removeEventListener('abort',abort); }
  }
  async revokeSessions(deviceSessionId?: string): Promise<void> { const entries = [...this.entries.values()].filter(entry=>deviceSessionId === undefined || entry.authority.deviceSessionId === deviceSessionId); for(const entry of entries) this.end(entry,'cancelled'); await Promise.allSettled(entries.flatMap(entry=>[entry.ready,entry.closure])); }
  close(): Promise<void> { if(this.closePromise) return this.closePromise; this.stopped = true; this.lifecycle.abort(); for(const entry of this.entries.values()) this.end(entry,'cancelled'); this.closePromise = (async()=>{ await Promise.allSettled([...this.pending]); await Promise.allSettled([...this.entries.values()].map(entry=>entry.closure)); for(const entry of this.entries.values()) { clearInterval(entry.timer); clearTimeout(entry.expiry); entry.state.text=''; } this.entries.clear(); })(); return this.closePromise; }
}
