import test from 'node:test';import assert from 'node:assert/strict';
import { ConnectionController,type ProbeResponse,type ProbeTransport } from '../src/connection.ts';
const origin='https://dots.example',api=origin+'/api/auth';
function response(body:unknown={enabled:true,authenticated:false,credentialKind:'connection_token',session:null},extra:Partial<ProbeResponse>={}):ProbeResponse{const r=Response.json(body);return{status:200,url:api,redirected:false,headers:r.headers,body:r.body,...extra};}
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{promise,resolve};}
test('preflight performs only a bounded credential-free GET and then validated login source',async()=>{const calls:unknown[]=[];const c=new ConnectionController(async(url,init)=>{calls.push([url,init]);return response();},()=>{});await c.connect(origin);assert.equal(c.snapshot().phase,'loading');assert.equal(c.snapshot().source,origin+'/login');const [url,init]=calls[0]as [string,any];assert.equal(url,api);assert.equal(init.method,'GET');assert.equal(init.credentials,'omit');assert.equal(init.redirect,'error');assert.deepEqual(init.headers,{accept:'application/json'});c.loaded(c.snapshot().epoch,origin+'/');assert.equal(c.snapshot().phase,'connected');c.dispose();});
test('invalid URL never reaches transport and no response credentials/session are kept',async()=>{let calls=0;const c=new ConnectionController(async()=>{calls++;return response();},()=>{});await c.connect('https://127.0.0.1');assert.equal(calls,0);assert.equal(c.snapshot().source,null);assert.equal(c.snapshot().error,'phone_loopback');await c.connect(origin);assert.ok(!JSON.stringify(c.snapshot()).includes('credentialKind'));c.dispose();});
test('auth-disabled, cookie-authenticated, redirected, wrong content and oversized responses fail closed',async()=>{const bad=[response({enabled:false}),response({enabled:true,authenticated:true,session:{secret:'do not keep'},credentialKind:'password'}),response(undefined,{redirected:true}),response(undefined,{url:'https://other.example/api/auth'}),response(undefined,{status:401}),response(undefined,{headers:new Headers({'content-type':'text/html'})}),response({padding:'x'.repeat(17000)}),response(undefined,{headers:new Headers({'content-type':'application/json','content-length':'100000'})})];for(const r of bad){const c=new ConnectionController(async()=>r,()=>{});await c.connect(origin);assert.equal(c.snapshot().phase,'offline');assert.equal(c.snapshot().source,null);c.dispose();}});
test('disconnect or a newer connect invalidates an unresolved probe and old WebView callbacks',async()=>{const first=deferred<ProbeResponse>();let calls=0;const c=new ConnectionController(async()=>++calls===1?first.promise:response(),()=>{});const pending=c.connect(origin),old=c.snapshot().epoch;c.disconnect();await c.connect(origin);const fresh=c.snapshot();first.resolve(response());await pending;assert.deepEqual(c.snapshot(),fresh);c.loaded(old,origin+'/');c.failed(old);assert.deepEqual(c.snapshot(),fresh);c.dispose();});
test('background suspension removes the page, fences callbacks, and never automatically resumes',async()=>{const c=new ConnectionController(async()=>response(),()=>{});await c.connect(origin);const epoch=c.snapshot().epoch;c.loaded(epoch,origin+'/');c.suspend();assert.equal(c.snapshot().phase,'suspended');assert.equal(c.snapshot().source,null);c.loaded(epoch,origin+'/');assert.equal(c.snapshot().phase,'suspended');c.disconnect();assert.equal(c.snapshot().origin,null);c.dispose();});
test('late untrusted loaded URL unmounts and cannot be overwritten by another old load',async()=>{const c=new ConnectionController(async()=>response(),()=>{});await c.connect(origin);const epoch=c.snapshot().epoch;c.loaded(epoch,'https://other.example/');assert.equal(c.snapshot().error,'navigation_blocked');assert.equal(c.snapshot().source,null);c.loaded(epoch,origin+'/');assert.equal(c.snapshot().phase,'offline');c.dispose();});
test('timeout becomes an offline state even if a faulty transport ignores abort',async()=>{const pending=deferred<ProbeResponse>();let signal!:AbortSignal;const c=new ConnectionController(async(_u,init)=>{signal=init.signal;return pending.promise;},()=>{},10);const p=c.connect(origin);await new Promise(r=>setTimeout(r,25));assert.equal(signal.aborted,true);assert.equal(c.snapshot().phase,'offline');pending.resolve(response());await p;assert.equal(c.snapshot().source,null);c.dispose();});
test('dispose fences late asynchronous results without publishing another state',async()=>{const pending=deferred<ProbeResponse>();let published=0;const c=new ConnectionController(async()=>pending.promise,()=>{published++;});const p=c.connect(origin);c.dispose();const count=published;pending.resolve(response());await p;assert.equal(published,count);});

test('a delayed native disconnect decision cannot tear down a newer connection',async()=>{const c=new ConnectionController(async()=>response(),()=>{});await c.connect(origin);const old=c.snapshot().epoch;await c.connect(origin);const current=c.snapshot();c.disconnect(old);assert.deepEqual(c.snapshot(),current);c.disconnect(current.epoch);assert.equal(c.snapshot().phase,'disconnected');c.dispose();});

test('metadata rejection cancels the unread response body and aborts native request ownership',async()=>{let cancelled=false,signal!:AbortSignal;const body=new ReadableStream<Uint8Array>({cancel(){cancelled=true;}});const c=new ConnectionController(async(_url,init)=>{signal=init.signal;return response(undefined,{headers:new Headers({'content-type':'text/plain'}),body});},()=>{});await c.connect(origin);assert.equal(c.snapshot().phase,'offline');assert.equal(cancelled,true);assert.equal(signal.aborted,true);c.dispose();});

test('deadline cancels a stalled response stream and settles the probe',async()=>{let cancelled=false;const body=new ReadableStream<Uint8Array>({cancel(){cancelled=true;}});const c=new ConnectionController(async()=>response(undefined,{body}),()=>{},10);await c.connect(origin);assert.equal(cancelled,true);assert.equal(c.snapshot().phase,'offline');assert.equal(c.snapshot().error,'unreachable');c.dispose();});
